function(lazperf_add_library _target _type)
    add_library(${_target} ${_type} ${ARGN})
    lazperf_library_compile_settings(${_target} ${_type})
    lazperf_install_library(${_target})
    if (WIN32)
        if (${_type} STREQUAL "SHARED")
            target_compile_definitions(${_target} PRIVATE LAZPERF_DLL_EXPORT)
        else()
            target_compile_definitions(${_target} PRIVATE LAZPERF_LIB_STATIC)
        endif()
    endif()
endfunction()
